version: '3.9'

services:
  postgres:
    image: postgis/postgis:13-3.1
    container_name: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: horrain
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    restart: always

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "fastapi"
    volumes:
      - .:/idk
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:1234@postgres:5432/horrain
    restart: always

volumes:
  postgres_data:
